[package]
name = "bindings"
version = "2025.11.7"
edition = "2024"

[dependencies]
spacetimedb-sdk = { git = "https://github.com/BitCraftToolBox/cacheless-rust-bindings" }
tokio = { version = "1.47.1", features = ["sync"] }
