[package]
name = "bindings"
version = "2026.2.6"
edition = "2024"

[dependencies]
spacetimedb-sdk = { git = "https://github.com/BitCraftToolBox/cacheless-rust-bindings", branch = "sdk" }
tokio = { version = "1.47.1", features = ["sync"] }
